### PR TITLE
build: add docker

### PR DESCRIPTION
**Pull request by alexsocha**

### CODE REVIEW

**Comment by archienorman11** [comment]
@alexsocha - do you plan to merge this PR any time soon? Best, Archie

**Comment by archienorman11** [comment]
FYI - I tested installing the build/add-docker branch and received:

```
ValueError: missing files: ['/tmp/pip-req-build-ojh9byae/algorithmx/nbextension/static/index.js', '/tmp/pip-req-build-ojh9byae/algorithmx/nbextension/static/extension.js']
```

**Comment by alexsocha** [comment]
I was away for the last few weeks, but now I should have more time to look at this. Thanks for catching that error. Yes, I plan to fix and merge it soon

**Comment by alexsocha** [comment]
It's finally ready to be merged! I've included some instructions in the README for installing/running the project either manually or with docker

**Pull request merged**
